apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: collector
spec:
  serviceName: collector-service
  replicas: 2
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: lab14-collector:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8815
            - containerPort: 9090
          env:
            - name: ETCD_URL
              value: "http://etcd-service:2379"
            - name: WINDOW_SIZE
              value: "10"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # collector-0 → SHARD_ID=0, collector-1 → SHARD_ID=1
          # В main.go парсить из POD_NAME: strings.Split(name, "-")[1]
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"